# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncom2.proto\x12\x05greet\".\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08greeting\x18\x02 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"E\n\x0c\x44\x65layedReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12$\n\x07request\x18\x02 \x03(\x0b\x32\x13.greet.HelloRequest\"\x18\n\x05msgOk\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x17\n\x07Usuario\x12\x0c\n\x04nome\x18\x01 \x01(\t2\xf7\x01\n\x07Greeter\x12*\n\x05Login\x12\x0e.greet.Usuario\x1a\x11.greet.HelloReply\x12;\n\x0fParrotSaysHello\x12\x13.greet.HelloRequest\x1a\x11.greet.HelloReply0\x01\x12\x43\n\x15\x43hattyClientSaysHello\x12\x13.greet.HelloRequest\x1a\x13.greet.DelayedReply(\x01\x12>\n\x10InteractingHello\x12\x13.greet.HelloRequest\x1a\x11.greet.HelloReply(\x01\x30\x01\x62\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_DELAYEDREPLY = DESCRIPTOR.message_types_by_name['DelayedReply']
_MSGOK = DESCRIPTOR.message_types_by_name['msgOk']
_USUARIO = DESCRIPTOR.message_types_by_name['Usuario']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'com2_pb2'
  # @@protoc_insertion_point(class_scope:greet.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'com2_pb2'
  # @@protoc_insertion_point(class_scope:greet.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

DelayedReply = _reflection.GeneratedProtocolMessageType('DelayedReply', (_message.Message,), {
  'DESCRIPTOR' : _DELAYEDREPLY,
  '__module__' : 'com2_pb2'
  # @@protoc_insertion_point(class_scope:greet.DelayedReply)
  })
_sym_db.RegisterMessage(DelayedReply)

msgOk = _reflection.GeneratedProtocolMessageType('msgOk', (_message.Message,), {
  'DESCRIPTOR' : _MSGOK,
  '__module__' : 'com2_pb2'
  # @@protoc_insertion_point(class_scope:greet.msgOk)
  })
_sym_db.RegisterMessage(msgOk)

Usuario = _reflection.GeneratedProtocolMessageType('Usuario', (_message.Message,), {
  'DESCRIPTOR' : _USUARIO,
  '__module__' : 'com2_pb2'
  # @@protoc_insertion_point(class_scope:greet.Usuario)
  })
_sym_db.RegisterMessage(Usuario)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=21
  _HELLOREQUEST._serialized_end=67
  _HELLOREPLY._serialized_start=69
  _HELLOREPLY._serialized_end=98
  _DELAYEDREPLY._serialized_start=100
  _DELAYEDREPLY._serialized_end=169
  _MSGOK._serialized_start=171
  _MSGOK._serialized_end=195
  _USUARIO._serialized_start=197
  _USUARIO._serialized_end=220
  _GREETER._serialized_start=223
  _GREETER._serialized_end=470
# @@protoc_insertion_point(module_scope)
