# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import comunicacao_pb2 as comunicacao__pb2


class ComunicarStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/comunicacao.Comunicar/Login',
                request_serializer=comunicacao__pb2.LoginRequest.SerializeToString,
                response_deserializer=comunicacao__pb2.LoginReply.FromString,
                )
        self.CadastroUsuario = channel.unary_unary(
                '/comunicacao.Comunicar/CadastroUsuario',
                request_serializer=comunicacao__pb2.LoginRequest.SerializeToString,
                response_deserializer=comunicacao__pb2.LoginReply.FromString,
                )
        self.ListagemDeitensTroca = channel.unary_unary(
                '/comunicacao.Comunicar/ListagemDeitensTroca',
                request_serializer=comunicacao__pb2.Vazia.SerializeToString,
                response_deserializer=comunicacao__pb2.ListReply.FromString,
                )


class ComunicarServicer(object):
    """The greeting service definition.
    """

    def Login(self, request, context):
        """Comunicação dupla
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CadastroUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListagemDeitensTroca(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComunicarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=comunicacao__pb2.LoginRequest.FromString,
                    response_serializer=comunicacao__pb2.LoginReply.SerializeToString,
            ),
            'CadastroUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CadastroUsuario,
                    request_deserializer=comunicacao__pb2.LoginRequest.FromString,
                    response_serializer=comunicacao__pb2.LoginReply.SerializeToString,
            ),
            'ListagemDeitensTroca': grpc.unary_unary_rpc_method_handler(
                    servicer.ListagemDeitensTroca,
                    request_deserializer=comunicacao__pb2.Vazia.FromString,
                    response_serializer=comunicacao__pb2.ListReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'comunicacao.Comunicar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Comunicar(object):
    """The greeting service definition.
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/comunicacao.Comunicar/Login',
            comunicacao__pb2.LoginRequest.SerializeToString,
            comunicacao__pb2.LoginReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CadastroUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/comunicacao.Comunicar/CadastroUsuario',
            comunicacao__pb2.LoginRequest.SerializeToString,
            comunicacao__pb2.LoginReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListagemDeitensTroca(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/comunicacao.Comunicar/ListagemDeitensTroca',
            comunicacao__pb2.Vazia.SerializeToString,
            comunicacao__pb2.ListReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
