# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comunicacao.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63omunicacao.proto\x12\x0b\x63omunicacao\"\x1f\n\x0cLoginRequest\x12\x0f\n\x07usuario\x18\x01 \x01(\t\"\x1d\n\nLoginReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8f\x01\n\tComunicar\x12;\n\x05Login\x12\x19.comunicacao.LoginRequest\x1a\x17.comunicacao.LoginReply\x12\x45\n\x0f\x43\x61\x64\x61stroUsuario\x12\x19.comunicacao.LoginRequest\x1a\x17.comunicacao.LoginReplyb\x06proto3')



_LOGINREQUEST = DESCRIPTOR.message_types_by_name['LoginRequest']
_LOGINREPLY = DESCRIPTOR.message_types_by_name['LoginReply']
LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'comunicacao_pb2'
  # @@protoc_insertion_point(class_scope:comunicacao.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginReply = _reflection.GeneratedProtocolMessageType('LoginReply', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREPLY,
  '__module__' : 'comunicacao_pb2'
  # @@protoc_insertion_point(class_scope:comunicacao.LoginReply)
  })
_sym_db.RegisterMessage(LoginReply)

_COMUNICAR = DESCRIPTOR.services_by_name['Comunicar']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUEST._serialized_start=34
  _LOGINREQUEST._serialized_end=65
  _LOGINREPLY._serialized_start=67
  _LOGINREPLY._serialized_end=96
  _COMUNICAR._serialized_start=99
  _COMUNICAR._serialized_end=242
# @@protoc_insertion_point(module_scope)
